name: flutter_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  get: ^4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:

    - family: SP400
      fonts:
        - asset: assets/fonts/SofiaProRegular.otf

    - family: SP500
      fonts:
        - asset: assets/fonts/SofiaProMedium.otf

    - family: SP600
      fonts:
        - asset: assets/fonts/SofiaProSemiBold.otf
